version: '3.1'

services:
  client:
    build: .
    volumes:
      - "./client:/app"
    ports:
      - "4200:4200"
    depends_on:
      - api

  api:
    build: .
    volumes:
      - "./server:/app"
    ports:
      - "5000:5000"